/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_


/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define MCLKIO_DIR_OUTPUT                                                  0x01u   /*!<@brief MCLK direction control.: The MCLK function is an output. */
#define PIO029_DIGIMODE_DIGITAL                                            0x01u   /*!<@brief Select Analog/Digital mode.: Digital mode. */
#define PIO029_FUNC_ALT1                                                   0x01u   /*!<@brief Selects pin function.: Alternative connection 1. */
#define PIO030_DIGIMODE_DIGITAL                                            0x01u   /*!<@brief Select Analog/Digital mode.: Digital mode. */
#define PIO030_FUNC_ALT1                                                   0x01u   /*!<@brief Selects pin function.: Alternative connection 1. */
#define PIO05_DIGIMODE_DIGITAL                                             0x01u   /*!<@brief Select Analog/Digital mode.: Digital mode. */
#define PIO05_FUNC_ALT1                                                    0x01u   /*!<@brief Selects pin function.: Alternative connection 1. */
#define PIO06_DIGIMODE_DIGITAL                                             0x01u   /*!<@brief Select Analog/Digital mode.: Digital mode. */
#define PIO06_FUNC_ALT1                                                    0x01u   /*!<@brief Selects pin function.: Alternative connection 1. */
#define PIO07_DIGIMODE_DIGITAL                                             0x01u   /*!<@brief Select Analog/Digital mode.: Digital mode. */
#define PIO07_FUNC_ALT1                                                    0x01u   /*!<@brief Selects pin function.: Alternative connection 1. */
#define PIO110_DIGIMODE_DIGITAL                                            0x01u   /*!<@brief Select Analog/Digital mode.: Digital mode. */
#define PIO110_FUNC_ALT4                                                   0x04u   /*!<@brief Selects pin function.: Alternative connection 4. */
#define PIO114_DIGIMODE_DIGITAL                                            0x01u   /*!<@brief Select Analog/Digital mode.: Digital mode. */
#define PIO114_FUNC_ALT0                                                   0x00u   /*!<@brief Selects pin function.: Alternative connection 0. */
#define PIO117_DIGIMODE_DIGITAL                                            0x01u   /*!<@brief Select Analog/Digital mode.: Digital mode. */
#define PIO117_FUNC_ALT4                                                   0x04u   /*!<@brief Selects pin function.: Alternative connection 4. */
#define PIO13_DIGIMODE_DIGITAL                                             0x01u   /*!<@brief Select Analog/Digital mode.: Digital mode. */
#define PIO13_FUNC_ALT0                                                    0x00u   /*!<@brief Selects pin function.: Alternative connection 0. */
#define PIO16_DIGIMODE_DIGITAL                                             0x01u   /*!<@brief Select Analog/Digital mode.: Digital mode. */
#define PIO16_FUNC_ALT2                                                    0x02u   /*!<@brief Selects pin function.: Alternative connection 2. */
#define PIO17_DIGIMODE_DIGITAL                                             0x01u   /*!<@brief Select Analog/Digital mode.: Digital mode. */
#define PIO17_FUNC_ALT2                                                    0x02u   /*!<@brief Selects pin function.: Alternative connection 2. */
#define PIO18_DIGIMODE_DIGITAL                                             0x01u   /*!<@brief Select Analog/Digital mode.: Digital mode. */
#define PIO18_FUNC_ALT2                                                    0x02u   /*!<@brief Selects pin function.: Alternative connection 2. */

/*! @name MCLK (number 10), MCLK */
#define BOARD_INITPINS_MCLK_PORT                                              1U   /*!<@brief PORT device index: 1 */
#define BOARD_INITPINS_MCLK_PIN                                              17U   /*!<@brief PIO1 GPIO pin index: 17 */

/*! @name PIO1_14 (number 57), SD_CSEL */
#define BOARD_INITPINS_SD_CSEL_GPIO                                         GPIO   /*!<@brief GPIO device name: GPIO */
#define BOARD_INITPINS_SD_CSEL_PORT                                           1U   /*!<@brief PORT device index: 1 */
#define BOARD_INITPINS_SD_CSEL_PIN                                           14U   /*!<@brief PIO1 GPIO pin index: 14 */

/*! @name PIO1_3 (number 17), CODEC_RESET */
#define BOARD_INITPINS_CODEC_RESET_GPIO                                     GPIO   /*!<@brief GPIO device name: GPIO */
#define BOARD_INITPINS_CODEC_RESET_PORT                                       1U   /*!<@brief PORT device index: 1 */
#define BOARD_INITPINS_CODEC_RESET_PIN                                        3U   /*!<@brief PIO1 GPIO pin index: 3 */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void); /* Function assigned for the Cortex-M0P */

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
