/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v7.0
processor: LPC51U68
package_id: LPC51U68JBD64
mcu_data: ksdk2_0
processor_version: 7.0.1
pin_labels:
- {pin_num: '17', pin_signal: PIO1_3/FC7_SSEL2/SCT0_OUT6/FC3_SCK/CTIMER0_CAP1/USB0_UP_LED/ADC0_6, label: CODEC_RESET, identifier: CODEC_RESET}
- {pin_num: '10', pin_signal: PIO1_17/MCLK/UTICK_CAP3, label: MCLK, identifier: MCLK}
- {pin_num: '57', pin_signal: PIO1_14/FC2_RXD_SDA_MOSI/SCT0_OUT7/FC7_TXD_SCL_MISO_WS, label: SD_POWER, identifier: SD_POWER}
- {pin_num: '13', pin_signal: PIO0_31/FC2_CTS_SDA_SSEL0/CTIMER0_CAP3/CTIMER0_MAT3/ADC0_2, label: SD_CSEL, identifier: SD_CSEL}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

#include "fsl_common.h"
#include "fsl_gpio.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 * 
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 * 
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void) {
    BOARD_InitPins();
}
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '39', peripheral: FLEXCOMM6, signal: RXD_SDA_MOSI_DATA, pin_signal: PIO0_5/FC6_RXD_SDA_MOSI_DATA/SCT0_OUT6/CTIMER0_MAT0}
  - {pin_num: '41', peripheral: FLEXCOMM6, signal: SCK, pin_signal: PIO0_7/FC6_SCK/SCT0_OUT0/CTIMER0_MAT2/CTIMER0_CAP2}
  - {pin_num: '40', peripheral: FLEXCOMM6, signal: TXD_SCL_MISO_WS, pin_signal: PIO0_6/FC6_TXD_SCL_MISO_WS/CTIMER0_MAT1/UTICK_CAP0}
  - {pin_num: '10', peripheral: SYSCON, signal: MCLK, pin_signal: PIO1_17/MCLK/UTICK_CAP3, direction: OUTPUT}
  - {pin_num: '27', peripheral: FLEXCOMM7, signal: RXD_SDA_MOSI_DATA, pin_signal: PIO1_7/FC7_RXD_SDA_MOSI_DATA/CTIMER1_MAT2/CTIMER1_CAP2/ADC0_10}
  - {pin_num: '26', peripheral: FLEXCOMM7, signal: SCK, pin_signal: PIO1_6/FC7_SCK/CTIMER1_CAP2/CTIMER1_MAT2/USB0_VBUS/ADC0_9}
  - {pin_num: '28', peripheral: FLEXCOMM7, signal: TXD_SCL_MISO_WS, pin_signal: PIO1_8/FC7_TXD_SCL_MISO_WS/CTIMER1_MAT3/CTIMER1_CAP3/ADC0_11}
  - {pin_num: '17', peripheral: GPIO, signal: 'PIO1, 3', pin_signal: PIO1_3/FC7_SSEL2/SCT0_OUT6/FC3_SCK/CTIMER0_CAP1/USB0_UP_LED/ADC0_6, direction: OUTPUT}
  - {pin_num: '44', peripheral: FLEXCOMM2, signal: TXD_SCL_MISO, pin_signal: PIO0_9/FC2_TXD_SCL_MISO/SCT0_OUT2/CTIMER3_CAP0/FC3_CTS_SDA_SSEL0}
  - {pin_num: '43', peripheral: FLEXCOMM2, signal: RXD_SDA_MOSI, pin_signal: PIO0_8/FC2_RXD_SDA_MOSI/SCT0_OUT1/CTIMER0_MAT3}
  - {pin_num: '45', peripheral: FLEXCOMM2, signal: SCK, pin_signal: PIO0_10/FC2_SCK/SCT0_OUT3/CTIMER3_MAT0}
  - {pin_num: '57', peripheral: GPIO, signal: 'PIO1, 14', pin_signal: PIO1_14/FC2_RXD_SDA_MOSI/SCT0_OUT7/FC7_TXD_SCL_MISO_WS, direction: OUTPUT}
  - {pin_num: '13', peripheral: GPIO, signal: 'PIO0, 31', pin_signal: PIO0_31/FC2_CTS_SDA_SSEL0/CTIMER0_CAP3/CTIMER0_MAT3/ADC0_2, direction: OUTPUT, gpio_init_state: 'true'}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void) { /* Function assigned for the Cortex-M0P */
  CLOCK_EnableClock(kCLOCK_Iocon);                           /* Enables the clock for the IOCON block. 0 = Disable; 1 = Enable.: 0x01u */
  CLOCK_EnableClock(kCLOCK_Gpio0);                           /* Enables the clock for the GPIO0 port registers. 0 = Disable; 1 = Enable. */
  CLOCK_EnableClock(kCLOCK_Gpio1);                           /* Enables the clock for the GPIO1 port registers. 0 = Disable; 1 = Enable. */

  gpio_pin_config_t SD_CSEL_io_config = {                    /* PORT0 PIN31 (number: 13) GPIO configuration structure */
    .pinDirection = kGPIO_DigitalOutput,
    .outputLogic = 1U
  };
  GPIO_PinInit(BOARD_INITPINS_SD_CSEL_GPIO, BOARD_INITPINS_SD_CSEL_PORT, BOARD_INITPINS_SD_CSEL_PIN, &SD_CSEL_io_config); /* Initialize GPIO functionality on pin PIO0_31 (number: 13) */
  gpio_pin_config_t CODEC_RESET_io_config = {                /* PORT1 PIN3 (number: 17) GPIO configuration structure */
    .pinDirection = kGPIO_DigitalOutput,
    .outputLogic = 0U
  };
  GPIO_PinInit(BOARD_INITPINS_CODEC_RESET_GPIO, BOARD_INITPINS_CODEC_RESET_PORT, BOARD_INITPINS_CODEC_RESET_PIN, &CODEC_RESET_io_config); /* Initialize GPIO functionality on pin PIO1_3 (number: 17) */
  gpio_pin_config_t SD_POWER_io_config = {                   /* PORT1 PIN14 (number: 57) GPIO configuration structure */
    .pinDirection = kGPIO_DigitalOutput,
    .outputLogic = 0U
  };
  GPIO_PinInit(BOARD_INITPINS_SD_POWER_GPIO, BOARD_INITPINS_SD_POWER_PORT, BOARD_INITPINS_SD_POWER_PIN, &SD_POWER_io_config); /* Initialize GPIO functionality on pin PIO1_14 (number: 57) */

  IOCON->PIO[0][10] = ((IOCON->PIO[0][10] &
    (~(IOCON_PIO_FUNC_MASK | IOCON_PIO_DIGIMODE_MASK)))      /* Mask bits to zero which are setting */
      | IOCON_PIO_FUNC(PIO010_FUNC_ALT1)                     /* Selects pin function.: PORT010 (pin 45) is configured as FC2_SCK */
      | IOCON_PIO_DIGIMODE(PIO010_DIGIMODE_DIGITAL)          /* Select Analog/Digital mode.: Digital mode. */
    );
  IOCON->PIO[0][31] = ((IOCON->PIO[0][31] &
    (~(IOCON_PIO_FUNC_MASK | IOCON_PIO_DIGIMODE_MASK)))      /* Mask bits to zero which are setting */
      | IOCON_PIO_FUNC(PIO031_FUNC_ALT0)                     /* Selects pin function.: PORT031 (pin 13) is configured as PIO0_31 */
      | IOCON_PIO_DIGIMODE(PIO031_DIGIMODE_DIGITAL)          /* Select Analog/Digital mode.: Digital mode. */
    );
  IOCON->PIO[0][5] = ((IOCON->PIO[0][5] &
    (~(IOCON_PIO_FUNC_MASK | IOCON_PIO_DIGIMODE_MASK)))      /* Mask bits to zero which are setting */
      | IOCON_PIO_FUNC(PIO05_FUNC_ALT1)                      /* Selects pin function.: PORT05 (pin 39) is configured as FC6_RXD_SDA_MOSI_DATA */
      | IOCON_PIO_DIGIMODE(PIO05_DIGIMODE_DIGITAL)           /* Select Analog/Digital mode.: Digital mode. */
    );
  IOCON->PIO[0][6] = ((IOCON->PIO[0][6] &
    (~(IOCON_PIO_FUNC_MASK | IOCON_PIO_DIGIMODE_MASK)))      /* Mask bits to zero which are setting */
      | IOCON_PIO_FUNC(PIO06_FUNC_ALT1)                      /* Selects pin function.: PORT06 (pin 40) is configured as FC6_TXD_SCL_MISO_WS */
      | IOCON_PIO_DIGIMODE(PIO06_DIGIMODE_DIGITAL)           /* Select Analog/Digital mode.: Digital mode. */
    );
  IOCON->PIO[0][7] = ((IOCON->PIO[0][7] &
    (~(IOCON_PIO_FUNC_MASK | IOCON_PIO_DIGIMODE_MASK)))      /* Mask bits to zero which are setting */
      | IOCON_PIO_FUNC(PIO07_FUNC_ALT1)                      /* Selects pin function.: PORT07 (pin 41) is configured as FC6_SCK */
      | IOCON_PIO_DIGIMODE(PIO07_DIGIMODE_DIGITAL)           /* Select Analog/Digital mode.: Digital mode. */
    );
  IOCON->PIO[0][8] = ((IOCON->PIO[0][8] &
    (~(IOCON_PIO_FUNC_MASK | IOCON_PIO_DIGIMODE_MASK)))      /* Mask bits to zero which are setting */
      | IOCON_PIO_FUNC(PIO08_FUNC_ALT1)                      /* Selects pin function.: PORT08 (pin 43) is configured as FC2_RXD_SDA_MOSI */
      | IOCON_PIO_DIGIMODE(PIO08_DIGIMODE_DIGITAL)           /* Select Analog/Digital mode.: Digital mode. */
    );
  IOCON->PIO[0][9] = ((IOCON->PIO[0][9] &
    (~(IOCON_PIO_FUNC_MASK | IOCON_PIO_DIGIMODE_MASK)))      /* Mask bits to zero which are setting */
      | IOCON_PIO_FUNC(PIO09_FUNC_ALT1)                      /* Selects pin function.: PORT09 (pin 44) is configured as FC2_TXD_SCL_MISO */
      | IOCON_PIO_DIGIMODE(PIO09_DIGIMODE_DIGITAL)           /* Select Analog/Digital mode.: Digital mode. */
    );
  IOCON->PIO[1][14] = ((IOCON->PIO[1][14] &
    (~(IOCON_PIO_FUNC_MASK | IOCON_PIO_DIGIMODE_MASK)))      /* Mask bits to zero which are setting */
      | IOCON_PIO_FUNC(PIO114_FUNC_ALT0)                     /* Selects pin function.: PORT114 (pin 57) is configured as PIO1_14 */
      | IOCON_PIO_DIGIMODE(PIO114_DIGIMODE_DIGITAL)          /* Select Analog/Digital mode.: Digital mode. */
    );
  IOCON->PIO[1][17] = ((IOCON->PIO[1][17] &
    (~(IOCON_PIO_FUNC_MASK | IOCON_PIO_DIGIMODE_MASK)))      /* Mask bits to zero which are setting */
      | IOCON_PIO_FUNC(PIO117_FUNC_ALT4)                     /* Selects pin function.: PORT117 (pin 10) is configured as MCLK */
      | IOCON_PIO_DIGIMODE(PIO117_DIGIMODE_DIGITAL)          /* Select Analog/Digital mode.: Digital mode. */
    );
  IOCON->PIO[1][3] = ((IOCON->PIO[1][3] &
    (~(IOCON_PIO_FUNC_MASK | IOCON_PIO_DIGIMODE_MASK)))      /* Mask bits to zero which are setting */
      | IOCON_PIO_FUNC(PIO13_FUNC_ALT0)                      /* Selects pin function.: PORT13 (pin 17) is configured as PIO1_3 */
      | IOCON_PIO_DIGIMODE(PIO13_DIGIMODE_DIGITAL)           /* Select Analog/Digital mode.: Digital mode. */
    );
  IOCON->PIO[1][6] = ((IOCON->PIO[1][6] &
    (~(IOCON_PIO_FUNC_MASK | IOCON_PIO_DIGIMODE_MASK)))      /* Mask bits to zero which are setting */
      | IOCON_PIO_FUNC(PIO16_FUNC_ALT2)                      /* Selects pin function.: PORT16 (pin 26) is configured as FC7_SCK */
      | IOCON_PIO_DIGIMODE(PIO16_DIGIMODE_DIGITAL)           /* Select Analog/Digital mode.: Digital mode. */
    );
  IOCON->PIO[1][7] = ((IOCON->PIO[1][7] &
    (~(IOCON_PIO_FUNC_MASK | IOCON_PIO_DIGIMODE_MASK)))      /* Mask bits to zero which are setting */
      | IOCON_PIO_FUNC(PIO17_FUNC_ALT2)                      /* Selects pin function.: PORT17 (pin 27) is configured as FC7_RXD_SDA_MOSI_DATA */
      | IOCON_PIO_DIGIMODE(PIO17_DIGIMODE_DIGITAL)           /* Select Analog/Digital mode.: Digital mode. */
    );
  IOCON->PIO[1][8] = ((IOCON->PIO[1][8] &
    (~(IOCON_PIO_FUNC_MASK | IOCON_PIO_DIGIMODE_MASK)))      /* Mask bits to zero which are setting */
      | IOCON_PIO_FUNC(PIO18_FUNC_ALT2)                      /* Selects pin function.: PORT18 (pin 28) is configured as FC7_TXD_SCL_MISO_WS */
      | IOCON_PIO_DIGIMODE(PIO18_DIGIMODE_DIGITAL)           /* Select Analog/Digital mode.: Digital mode. */
    );
  SYSCON->MCLKIO = ((SYSCON->MCLKIO &
    (~(SYSCON_MCLKIO_DIR_MASK)))                             /* Mask bits to zero which are setting */
      | SYSCON_MCLKIO_DIR(MCLKIO_DIR_OUTPUT)                 /* MCLK direction control.: The MCLK function is an output. */
    );
}

/* clang-format on */
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
